allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

// Fix for plugins that don't specify namespace (required by AGP 8.0+)
subprojects { sub ->
    sub.plugins.withId("com.android.library") {
        def manifestFile = file("${sub.projectDir}/src/main/AndroidManifest.xml")
        if (manifestFile.exists()) {
            def manifest = new XmlSlurper().parse(manifestFile)
            def packageName = manifest.@package.toString()
            if (packageName && !packageName.isEmpty()) {
                sub.android.namespace = packageName
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
